ifdef::pmglogo[]
image:./images/proxmox-logo.svg[] pass:[<br>] Proxmox Mail Gateway Administration Guide
=======================================================================================
endif::pmglogo[]
ifndef::pmglogo[]
Proxmox Mail Gateway Administration Guide
=========================================
endif::pmglogo[]
:doctype:   book
:title: Proxmox Mail Gateway Administration Guide
:toc:
:numbered:
:data-uri:
:icons:
ifndef::wiki[]
ifndef::manvolnum[]
:pmg-toplevel:

// Push titles down one level.
:leveloffset: 1

include::pmg-intro.adoc[]

include::pmg-planning-deployment.adoc[]

include::pmg-installation.adoc[]

include::pmgconfig.adoc[]

include::pmg-mail-filter.adoc[]

include::pmgbackup.adoc[]

include::pmgcm.adoc[]

// Return to normal title levels.
:leveloffset: 0


Important Service Daemons
-------------------------

:leveloffset: 2

include::pmgdaemon.adoc[]

include::pmgproxy.adoc[]

include::pmg-smtp-filter.adoc[]

include::pmgpolicy.adoc[]

include::pmgtunnel.adoc[]

include::pmgmirror.adoc[]

:leveloffset: 0


Useful Command Line Tools
-------------------------

:leveloffset: 2
include::pmgdb.adoc[]

include::pmgsh.adoc[]

include::pmgversion.adoc[]

include::pmgsubscription.adoc[]

include::pmgperf.adoc[]

include::pmgqm.adoc[]

include::pmgreport.adoc[]

include::pmgupgrade.adoc[]

:leveloffset: 0


[[nmap]]
`nmap` - Port Scans
-------------------

`nmap` is designed to allow system administrators to scan large
networks to determine which hosts are up and what services they are
offering. You can use nmap to test your firewall setting, for example
to see if the required ports are open.

.Test Razor port (tcp port 2703):
----
# nmap -P0 -sS -p 2703 c301.cloudmark.com

Starting Nmap 5.00 ( http://nmap.org ) at 2012-07-31 11:10 CEST
Interesting ports on c301.cloudmark.com (208.83.137.114):
PORT     STATE SERVICE
2703/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.17 seconds
----

See the manual page (`man nmap`) for more information about nmap.


:leveloffset: 1

include::pmg-bibliography.adoc[]

:leveloffset: 0

[appendix]
SSL certificate
---------------

Access to the administration web interface is always done via
`https`. The default certificate is never valid for your browser and
you get always warnings.

If you want to get rid of these warnings, you have to generate a valid
certificate for your server.

Login to your Proxmox via ssh or use the console:

----
openssl req -newkey rsa:2048 -nodes -keyout key.pem -out req.pem
----

Follow the instructions on the screen, see this example:

----
Country Name (2 letter code) [AU]: AT
State or Province Name (full name) [Some-State]:Vienna
Locality Name (eg, city) []:Vienna
Organization Name (eg, company) [Internet Widgits Pty Ltd]: Proxmox GmbH
Organizational Unit Name (eg, section) []:Proxmox Mail Gateway
Common Name (eg, YOUR name) []: yourproxmox.yourdomain.com
Email Address []:support@yourdomain.com

Please enter the following 'extra' attributes to be sent with your certificate request
A challenge password []: not necessary
An optional company name []: not necessary
----

After you finished this certificate request you have to send the file
`req.pem` to your Certification Authority (CA). The CA will issue the
certificate (BASE64 encoded) based on your request – save this file as
`cert.pem` to your Proxmox.

To activate the new certificate, do the following on your Proxmox:

----
cat key.pem cert.pem >/etc/pmg/pmg-api.pem
----

The restart the API servers

----
systemctl restart pmgproxy
----

Test your new certificate by using your browser.

NOTE: To transfer files from and to your Proxmox, you can use secure
copy: If you desktop is Linux, you can use the `scp` command line
tool. If your desktop PC is windows, please use a scp client like
WinSCP (see http://winscp.net/).


[appendix]
Command Line Interface
----------------------

*pmgbackup* - Proxmox Mail Gateway Backup and Restore Utility
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::pmgbackup.1-synopsis.adoc[]


*pmgcm* - Proxmox Mail Gateway Cluster Management Toolkit
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::pmgcm.1-synopsis.adoc[]


*pmgsh* - API Shell
~~~~~~~~~~~~~~~~~~~

include::pmgsh.1-synopsis.adoc[]


*pmgperf* - Proxmox Simple Performance Benchmark
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::pmgperf.1-synopsis.adoc[]


*pmgconfig* - Configuration Management Toolkit
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::pmgconfig.1-synopsis.adoc[]


*pmgdb* - Database Management Toolkit
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::pmgdb.1-synopsis.adoc[]


[appendix]
Service Daemons
---------------

*pmgdaemon* - {pmg} API Daemon
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::pmgdaemon.8-synopsis.adoc[]


*pmgproxy* - {pmg} API Proxy Daemon
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::pmgproxy.8-synopsis.adoc[]


*pmg-smtp-filter* - Proxmox SMTP Filter Daemon
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::pmg-smtp-filter.8-synopsis.adoc[]


*pmgpolicy* - {pmg} Policy Daemon
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::pmgpolicy.8-synopsis.adoc[]


*pmgtunnel* - Cluster Tunnel Daemon
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::pmgtunnel.8-synopsis.adoc[]


*pmgmirror* - Database Mirror Daemon
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::pmgmirror.8-synopsis.adoc[]


[appendix]
include::pmg-rule-macros.adoc[]

[appendix]
Configuration Files
-------------------

:leveloffset: 2

include::pmg.conf.adoc[]

include::cluster.conf.adoc[]

include::user.conf.adoc[]

include::ldap.conf.adoc[]

:leveloffset: 0

:leveloffset: 1

[appendix]
include::GFDL.adoc[]

:leveloffset: 0

endif::manvolnum[]
endif::wiki[]
