Quick Start Guide
=================

Experienced users can use this guide for a quick installation. For
detailed instructions please read the whole documentation.


. Download ISO from Download http://www.proxmox.com
+
NOTE: There is one ISO image for download covering all versions and
features.

. Burn the downloaded ISO image to a CD or create a
xref:create_bootable_usb[bootable USB stick].

. Boot from this CD/USB stick on your dedicated hardware - see xref:system_requirements[System requirements].

[thumbnail="pmg-grub-menu.ppm"]

. Follow the instructions on the graphical screen.
+
CAUTION: All existing data on your hard disk will be lost!

. After reboot, go to your desktop PC and point your browser to the
given IP address.

. Login and upload subscription key.

. Check the IP configuration and hostname.

. Check and save the Time Zone.

. Check your xref:firewall_settings[Firewall settings].

. Configure {pmg} to forward the incoming SMTP traffic to your Mail
server ('Configuration/Mail Proxy/Default Relay') - 'Default
Relay' is your e-mail server.

. Configure your e-mail server to send all outgoing messages through
your {pmg} ('Smart Host', port 26 by default) - see
xref:fitering_outgoing_mail[Filtering outgoing e-mails].

For detailed deployment scenarios see the "{pmg} Deployment Guide".

If the installation succeeds you have to route all your incoming and
outgoing e-mail traffic to the Mail Gateway. For incoming traffic you
have to configure your firewall and/or DNS settings. For outgoing
traffic you need to change the existing e-mail server configuration.

