[bibliography]
Bibliography
============
ifndef::manvolnum[]
:pmg-toplevel:
endif::manvolnum[]

[bibliography]
.Books about mail processing technology

- [[[KyleDDent04]]] Kyle D Dent.
  'Postfix: The Definitive Guide'.
   O'Reilly & Associates, 2004.
   ISBN 978-0596002121

- [[[Schwartz04]]] Alan Schwartz.
  'SpamAssassin'.
   O'Reilly & Associates, 2004.
   ISBN 978-0596007072


[bibliography]
.Books about related technology

- [[[Hertzog13]]] Raphaël Hertzog & Roland Mas.
  https://debian-handbook.info/download/stable/debian-handbook.pdf[The Debian Administrator\'s Handbook: Debian Jessie from Discovery to Mastery],
  Freexian, 2013.
  ISBN 979-1091414050
  
- [[[Bir96]]] Kenneth P. Birman.
  'Building Secure and Reliable Network Applications'.
  Manning Publications Co, 1996.
  ISBN 978-1884777295

- [[[Walsh10]]] Norman Walsh.
  'DocBook 5: The Definitive Guide'.
  O'Reilly & Associates, 2010.
  ISBN 978-0596805029

- [[[Richardson07]]] Leonard Richardson & Sam Ruby.
  'RESTful Web Services'.
  O'Reilly Media, 2007.
  ISBN 978-0596529260

- [[[Friedl97]]] Jeffrey E. F. Friedl.
  'Mastering Regular Expressions'.
  O'Reilly & Associates, 2006.
  ISBN 978-0596528126

- [[[Mauerer08]]] Wolfgang Mauerer.
  'Professional Linux Kernel Architecture'.
  John Wiley & Sons, 2008.
  ISBN 978-0470343432

- [[[Loshin03]]] Pete Loshin,
  'IPv6: Theory, Protocol, and Practice, 2nd Edition'.
  Morgan Kaufmann, 2003.
  ISBN 978-1558608108

- [[[Loeliger12]]] Jon Loeliger & Matthew McCullough.
  'Version Control with Git: Powerful tools and techniques for
   collaborative software development'.
  O'Reilly and Associates, 2012.
  ISBN 978-1449316389

- [[[Ahmed16]]] Wasim Ahmed.
  'Mastering Proxmox - Second Edition'.
  Packt Publishing, 2016.
  ISBN 978-1785888243


[bibliography]
.Books about related topics

- [[[Bessen09]]] James Bessen & Michael J. Meurer,
  'Patent Failure: How Judges, Bureaucrats, and Lawyers Put Innovators at Risk'.
  Princeton Univ Press, 2009.
  ISBN 978-0691143217
